name: Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Install ChromeDriver and Firefox for browser testing
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v1
      with:
        chromedriver-version: latest

    - name: Set up geckodriver (Firefox)
      uses: mozilla/geckodriver-action@v1.2.0

    # Cache Maven dependencies to speed up build times
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven

    # Run the tests using Maven
    - name: Run tests
      run: mvn clean test
