name: Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Install Java JDK
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'

    # Install Chrome and Chromedriver
    - name: Install Chrome and Chromedriver
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -y chromium-chromedriver
        sudo ln -sf /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    # Install Geckodriver for Firefox
    - name: Install Geckodriver
      run: |
        GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep "tag_name" | cut -d '"' -f 4)
        wget "https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz"
        tar -xvzf geckodriver-*.tar.gz
        sudo mv geckodriver /usr/local/bin/
        geckodriver --version

    # Set up Selenium
    - name: Install Selenium
      run: |
        pip install selenium

    # Run tests
    - name: Run Selenium tests
      run: |
        java -cp "path/to/your/test/classes" org.testng.TestNG testng.xml

    # Post-job cleanup
    - name: Cleanup
      run: |
        sudo rm -rf geckodriver-*.tar.gz
        sudo apt-get clean
